apiVersion: batch/v1
kind: Job
metadata:
  name: $(trainingName)-gh-job
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: $(trainingName)-gh-job
          image: bq-extract
          volumeMounts:
            - name: secret-volume
              mountPath: /secret/gcp-credentials
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/gcp-credentials/$(secretName).json
      restartPolicy: OnFailure
      volumes:
        - name: secret-volume
          secret:
            secretName: $(secretName)
