apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- deployment.yaml
images:
- name: bq-extract
  newName: gcr.io/$(projectName)/kf-steps/bq-extract:v8
vars:
- fieldref:
    fieldPath: data.secretName
  name: secretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: github-data-extract
- fieldref:
    fieldPath: data.trainingName
  name: trainingName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: github-data-extract
- fieldref:
    fieldPath: data.projectName
  name: projectName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: github-data-extract
configurations:
- params.yaml
configMapGenerator:
- literals:
  - secretName=user-gcp-sa
  - projectName=boos-demo-projects-are-rad
  - trainingName=gh-data-extract
  name: github-data-extract
